---
# layout: cv
format:
  html:
    page-layout: custom
    include-in-header:
    - text: |
        <head>
            <meta charset="utf-8" />
            <title> Theo Rashid | CV </title>
            <link href="media/tr-screen.css" type="text/css" rel="stylesheet" media="screen">
            <link href="media/tr-print.css" type="text/css" rel="stylesheet" media="print">
        </head>
        <h1> Theo Rashid </h1>
        <div align="left", id="webaddress">
            <a href="mailto:theoaorashid@gmail.com">theoaorashid@gmail.com</a>
            | <a href="https://theorashid.github.io">theorashid.github.io</a>
        </div>
        </html>
# title: Theo Rashid
---
<!-- # Theo Rashid -->
<!-- Physicist, Mathematician, Statistician. -->

## Current

`2023-`
__Research Associate, University of Oxford__

- Modelling food insecurity, in [Seth Flaxman's](https://sethrf.com) group in collaboration with the UN World Food Programme.

## Experience

`2022`
Applied Scientist intern, __Amazon__, Seattle

- Implementing multivariate probabilistic time series models to forecast product demand in the grocery sector.

`Summer 2019`
Business Analyst, __Deecon Consulting__, London

`Summer 2018`
Researcher, __Space and Atmospheric Physics Group__, Department of Physics, Imperial College London

<!-- `Summer 2014`
Nuffield Research Placement, __Spectroscopy and Dynamics Group__, Department of Chemistry, University of Leicester -->

## Education

`2019-2023`
__PhD in Epidemiology & Biostatistics, Imperial College London__

- Thesis title: Spatiotemporal modelling of all-cause and cause-specific mortality in England
<!-- - Scalable Bayesian models for estimating life expectancy over space and time -->
- Supervised by [Majid Ezzati](https://www.imperial.ac.uk/people/majid.ezzati), [James Bennett](https://www.imperial.ac.uk/people/umahx99) and [Seth Flaxman](https://sethrf.com), funded by the President’s Scholarship

`2015-19`
__MSci in Physics with Theoretical Physics, Imperial College London__

- First Class Honours

<!-- `2008-15`
__Leicester Grammar School__
- A Levels: Mathematics (A<sup>*</sup>), Further Mathematics (A<sup>*</sup>), Physics (A<sup>*</sup>), Chemistry (A<sup>*</sup>) -->
<!-- - GCSEs: 10 A<sup>*</sup>s including English -->

## Selected Publications

`2023`
__Rashid, T.__, Bennett, J.E. _et al._ (2023). [Changes in life expectancy and house prices in London from 2002 to 2019: hyper-resolution spatiotemporal analysis of death registration and real estate data](https://www.thelancet.com/journals/lanepe/article/PIIS2666-7762(22)00276-9/fulltext). _The Lancet Regional Health Europe_, 27, 100580.

`2022`
Semenova, E., Xu, Y., Howes, A.T., __Rashid, T.__ _et al._ (2022). [PriorVAE: encoding spatial priors with variational autoencoders for small-area estimation](https://royalsocietypublishing.org/doi/10.1098/rsif.2022.0094). _Journal of the Royal Society Interface_, 19, 20220094.

`2021`
__Rashid, T.__, Bennett, J.E. _et al._ (2021). [Life expectancy and risk of death in 6791 communities in England from 2002 to 2019: high-resolution spatiotemporal analysis of civil registration data](https://www.thelancet.com/journals/lanpub/article/PIIS2468-2667(21)00205-X/fulltext). _The Lancet Public Health_, 6, e805 - e816.

`2020`
Kontis, V., Bennett, J.E., __Rashid, T.__ _et al._ (2020). [Magnitude, demographics and dynamics of the effect of the first wave of the COVID-19 pandemic on all-cause mortality in 21 industrialized countries](https://www.nature.com/articles/s41591-020-1112-0). _Nature Medicine_, 26, 1919–1928.

Wang, S., __Rashid, T.__ _et al._ (2020). [A shortening of the lifecycle of major tropical cyclones](https://agupubs.onlinelibrary.wiley.com/doi/abs/10.1029/2020GL088589). _Geophysical Research Letters_, 47, e2020GL088589.

<!-- A list is also available [online](https://theorashid.github.io/#publications) -->

## Talks

`2022`
The changing mortality patterns in 6791 communities in England, __6th Human Mortality Database Symposium, INED__

`2021`
High-resolution spatiotemporal analysis in 6791 English areas reveals declines in life expectancy, __European Public Health Conference__

Life expectancy inequality in London, __Conference of the International Society for Environmental Epidemiology__

High resolution analysis reveals widening 30-year life expectancy gap within London, __International Conference on Urban Health__

## Teaching

`2023`
Instructor, __Bayesian Modelling for Environmental Health__ workshop, Columbia University

`2021-23`
Head Teaching Assistant, __Population Health__ in the Health Data Analytics and Machine Learning MSc, Imperial College London

`2021`
Teaching Assistant, __Statistics for Public Health__ in the MPH, Imperial College London

## Skills

### Statistical

Bayesian modelling, machine learning, forecasting, spatiotemporal statistics, probabilistic programming

### Computational

Highly proficient in R, python

Experience in Julia, Stan, shell/ssh, git, high performance computing, data visualisation, Markdown, LaTeX, html, D3.js, CAD

### Languages

French (C1/B2)

<!-- ### Footer

References on request. Last updated: July 2021 -->
